service: xintern-reviews-api
#app: your-app-name
#tenant: your-tenant-name

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  environment:
    MONGO_URL: "${self:custom.tokens.MONGO_TEST}"

package:
  exclude:
    - tokens.yml

custom:
  stage: ${opt:stage, self:provider.stage}
  tokens: ${file(tokens.yml):${self:custom.stage}}

functions:
  createReview:
    handler: api-handler.createReview
    events:
      - http:
          path: review
          method: POST
          cors: true

  updateReview:
    handler: api-handler.updateReview
    events:
      - http:
          path: review/{review_id}
          method: PATCH
          request:
            parameters:
              paths:
                review_id: true
          cors: true
  
  getFlaggedReviews:
    handler: api-handler.getFlaggedReviews
    events:
      - http:
          path: review/create
          method: GET
          cors: true

  updateCompany:
    handler: api-handler.updateCompany
    events:
      - http:
          path: review/{review_id}/company/{company_id}
          method: PATCH
          request:
            parameters:
              paths:
                review_id: true
                company_id: true
          cors: true

  updateRating:
    handler: api-handler.updateRating
    events:
      - http:
          path: review/{review_id}/rating/{rating_id}
          method: PATCH
          request:
            parameters:
              paths:
                review_id: true
                rating_id: true
          cors: true

  deleteReview:
    handler: api-handler.deleteReview
    events:
      - http:
          path: review/{review_id}
          method: DELETE
          request:
            parameters:
              paths:
                review_id: true
          cors: true
  getPopulatedReviews:
    handler: api-handler.getPopulatedReviews
    events:
      - http:
          path: populated-review/{review_id}
          method: GET
          request:
            parameters:
              paths:
                review_id: true
          cors: true

  deleteComment:
    handler: api-handler.deleteComment
    events:
      - http:
          path: comment/{comment_id}
          method: PATCH
          request:
            parameters:
              paths:
                comment_id: true
          cors: true

  createComment:
    handler: api-handler.createComment
    events:
      - http:
          path: review/{review_id}/comment
          method: POST
          request:
            parameters:
              paths:
                review_id: true
          cors: true
    
  updateComment:
    handler: api-handler.updateComment
    events:
      - http:
          path: review/{review_id}/comment/{comment_id}
          method: PATCH
          request:
            parameters:
              paths:
                review_id: true
                comment_id: true
          cors: true
    
  upvoteReview:
    handler: api-handler.upvoteReview
    events:
      - http:
          path: review/{review_id}/upvote
          method: PATCH
          request:
            parameters:
              paths:
                review_id: true
          cors: true
    
  downvoteReview:
    handler: api-handler.downvoteReview
    events:
      - http:
          path: review/{review_id}/downvote
          method: PATCH
          request:
            parameters:
              paths:
                review_id: true
          cors: true
  upvoteComment:
    handler: api-handler.upvoteComment
    events:
      - http:
          path: review/{review_id}/comment/{comment_id}/upvote
          method: PATCH
          request:
            parameters:
              paths:
                review_id: true
                comment_id: true
          cors: true
    
  downvoteComment:
    handler: api-handler.downvoteComment
    events:
      - http:
          path: review/{review_id}/comment/{comment_id}/downvote
          method: PATCH
          request:
            parameters:
              paths:
                review_id: true
                comment_id: true
          cors: true

  addCompany:
    handler: api-handler.addCompany
    events:
      - http:
          path: company
          method: POST
          cors: true

  deleteCompany:
    handler: api-handler.deleteCompany
    events:
      - http:
          path: company/{company_id}
          method: DELETE
          request:
            parameters:
              paths:
                company_id: true
          cors: true

  getReviewsByCompany:
    handler: api-handler.getReviewsByCompany
    events:
      - http:
          path: company/{company_id}/reviews
          method: GET
          request:
            parameters:
              paths:
                company_id: true
          cors: true

  getRecentReviews:
    handler: api-handler.getRecentReviews
    events:
      - http:
          path: review/recent
          method: GET
          cors: true

  getTopCompanies:
    handler: api-handler.getTopCompanies
    events:
      - http:
          path: topCompanies
          method: GET
          cors: true

  getAllCompanies:
    handler: api-handler.getAllCompanies
    events:
      - http:
          path: company/all
          method: GET
          cors: true
  
  getReviewById:
    handler: api-handler.getReviewById
    events:
      - http:
          path: review/{review_id}
          method: GET
          request:
            parameters:
              paths:
                review_id: true
          cors: true

  getPopulatedComments:
    handler: api-handler.getPopulatedComments
    events:
      - http:
          path: comments/{review_id}
          method: GET
          request:
            parameters:
              paths:
                review_id: true
          cors: true

  flagReview:
    handler: api-handler.flagReview
    events:
      - http:
          path: review/{review_id}/flag
          method: PATCH
          cors: true
  flagReview:
    handler: api-handler.flagReview
    events:
      - http:
          path: review/{review_id}/comment/{comment_id}/flag
          method: PATCH
          cors: true

  # addCommentToReview:
  #     handler: api-handler.addCommentToReview
  #     events:
  #       - http:
  #           path: link-comment
  #           method: POST
  #           cors: true

  # addCompany:
  #   handler: api-handler.addCompany
  #   events:
  #     - http:
  #         path: company
  #         method: POST
  #         cors: true