version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: npm i
      - run: npm test
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - test