version: 2
jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 
          name: run tests
          command: |
              set -e
              npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test